replicaCount: 1
configMapName: fravega-wms-gitlab-cherry-pick-workflow-dev-config
secretName: fravega-wms-gitlab-cherry-pick-workflow-dev-secrets

image:
  repository: ''
  pullPolicy: IfNotPresent
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ''

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: ''
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: '360s'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '360s'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '360s'
    # kubernetes.io/tls-acme: "true"

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}